baseURL = 'https://enkidu.site/'
title = 'Enkidu'
theme = "reimu"
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'

[languages]
    [languages.zh-CN]
        languageName = '简体中文'
        hasCJKLanguage = true
        contentDir = 'content/zh-cn'
        weight = 1
        
    [languages.en]
        languageName = "English" 
        hasCJKLanguage = false
        contentDir = 'content/en'
        weight = 2

[outputs]
    home = ["Algolia", "HTML"]
    [outputFormats.Algolia]
        baseName = "algolia"
        isPlainText = true
        mediaType = "application/json"
        notAlternative = true